name: phaser_example
publish_to: none
dependencies:
    phaser:
      path: ../dart_phaser
dev_dependencies:
    browser: ^0.10.0
    dart_to_js_script_rewriter: ^1.0.0
transformers:
- dart_to_js_script_rewriter